language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - mkdir -p ./tests/build/logs
  - ./tests/install.sh
  - composer global require drush/drush:dev-master --prefer-source

script:
  - ./tests/run-tests.sh --coverage-clover build/logs/clover.xml
  - ./tests/run-simpletests.sh

after_script:
  - cd ./tests
  - php vendor/bin/coveralls -v

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0c7b5a71d435245837a1
    on_success: always
    on_failure: always
    on_start: false
