# .travis.yml - File for Travis CI
#
# Based for simpletest upon:
#   https://github.com/sonnym/travis-ci-drupal-module-example

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

env:
  # add composer's global bin directory to the path
  # see: https://github.com/drush-ops/drush#install---composer
  - PATH="$PATH:$HOME/.composer/vendor/bin"

mysql:
  database: drupal_travis_db
  username: root
  encoding: utf8

install:
  - ./tests/install.sh
  - ./tests/drupal-travis-integration/install.sh

before_script:
  - mkdir -p ./tests/build/logs
  # Install drupal and run web server: $module_name $db_name $db_url
  - ./tests/drupal-travis-integration/before-script.sh "service_container" "drupal_travis_db" "mysql://root:@127.0.0.1/drupal_travis_db"

script:
  - ./tests/run-tests.sh --coverage-clover build/logs/clover.xml
  - ./tests/drupal-travis-integration/run-simpletests.sh --verbose --color --concurrency 4 --php $(which php) --url "http://127.0.0.1:8080" "service_container"

after_script:
  - cd ./tests
  - php vendor/bin/coveralls -v

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0c7b5a71d435245837a1
    on_success: always
    on_failure: always
    on_start: false
