language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script: "./tests/install.sh"

script:
  - ./tests/run-tests.sh
  - ./tests/run-simpletests.sh

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0c7b5a71d435245837a1
    on_success: always
    on_failure: always
    on_start: false
