<?php

/**
 * Implements hook_ctools_plugin_directory().
 */
function service_container_test_ctools_ctools_plugin_directory($owner, $plugin_type) {
  return 'src/plugins/' . str_replace("\\", DIRECTORY_SEPARATOR, $plugin_type);
}

/**
 * Implements hook_ctools_plugin_type().
 */
function service_container_test_ctools_ctools_plugin_type() {
  return array(
    'ServiceContainerTestCtoolsPlugin' => array(
      'use hooks' => FALSE,
      'extension' => 'php',
    ),
  );
}
