<?php
/**
 * @file
 * Main module file for the service_container_libraries module.
 */

// -----------------------------------------------------------------------
// Contrib Hooks

/**
 * Implements hook_libraries_info().
 */
function service_container_libraries_libraries_info() {
  $libraries = array();

  foreach (module_list() as $module) {
    $filename = drupal_get_filename('module', $module);
    $libraries_file = dirname($filename) . "/$module.libraries.yml";
    if (file_exists($libraries_file)) {
      $libraries = array_merge(
        $libraries,
        \Drupal\Component\Serialization\Yaml::decode(file_get_contents($libraries_file))
      );
    }
  }

  return $libraries;
}
